# Generated by Django 2.1.7 on 2019-03-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardproductexpendable',
            name='diameter',
        ),
        migrations.RemoveField(
            model_name='standardproductexpendable',
            name='length',
        ),
        migrations.RemoveField(
            model_name='standardproductexpendable',
            name='symbol',
        ),
        migrations.AddField(
            model_name='expendable',
            name='estimated_delivery',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expendable',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standardproduct',
            name='code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expendable',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
