# Generated by Django 2.1.7 on 2019-03-15 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20190315_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expendable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.Expendable')),
            ],
        ),
    ]
