# Generated by Django 2.1.7 on 2019-03-21 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegularAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='purchases.Action')),
                ('duration', models.IntegerField()),
            ],
            bases=('purchases.action',),
        ),
        migrations.CreateModel(
            name='SubcontractAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='purchases.Action')),
                ('expendable_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='purchases.Expendable')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.Contract')),
            ],
            bases=('purchases.action',),
        ),
        migrations.AddField(
            model_name='action',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.Operation'),
        ),
    ]
