# Generated by Django 2.1.3 on 2018-11-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20181115_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FilePathField(path='/work/django_projects/test_project/media', recursive=True),
        ),
    ]
